version: '3.5'

services:
  db:
    image: postgres:14.9-bullseye
    container_name: postgres-14.9-dev
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - postgres-compose-network

  server:
    build: ./
    working_dir: /api/api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8082:8000
    env_file:
      - .env.dev
    networks:
      - postgres-compose-network
    profiles:
      - dev # docker-compose --profile dev up 
    depends_on:
      - db

networks: 
  postgres-compose-network:
    driver: bridge